### ISSUE TITLE
support numpy values as inputs

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kfactory#223]
how can we support numpy arrays as cell inputs?

**Comment by sebastian-goeldi** [comment]
tl;dr give it something hashable or one of the types that are autoconverted ;)

**Comment by joamatab** [comment]
I see, it's a bit of an edge case, we wrote custom serializers in gdsfactory but it's a pain to maintain :)

**Comment by sebastian-goeldi** [comment]
yeah, I agree. The reason I also push back hard on this: if you ever pass numpy values to any klayout objects, they will complain with a cryptic error message

```pycon
>>> import klayout.db as kdb
>>> import numpy as np
>>> 
>>> kdb.Trans(1,1)
r0 1,1
>>> kdb.Trans(np.int(1),1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sgoeldi/miniconda3/envs/kf/lib/python3.12/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```
