### ISSUE TITLE
invalid syntax error when importing kfactory

### ISSUE THREAD

**Issue by albe-jj** [gdsfactory/kfactory#69]
`import kfactory`

gives error:

```
Traceback (most recent call last):

  File "C:\Users\atosato\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "C:\Users\atosato\AppData\Local\Temp\ipykernel_25776\1518496074.py", line 1, in <cell line: 1>
    from kfactory import KCell

  File "C:\Users\atosato\Anaconda3\lib\site-packages\kfactory\__init__.py", line 8, in <module>
    from .kcell import (

  File "C:\Users\atosato\Anaconda3\lib\site-packages\kfactory\kcell.py", line 1558
    match x0_yml:
          ^
SyntaxError: invalid syntax
```

kfactory version 0.5.7

**Comment by sebastian-goeldi** [comment]
Are you using python >= 3.10?

match case only works in 3.10+

**Comment by albe-jj** [comment]
Thanks for the reply, no I was using python 3.8. I just realized that matching statement was introduce only in python 3.10. 
Maybe the line below could be changed to reflect this requirement? 
https://github.com/gdsfactory/kfactory/blob/3d59445e914814a010f91ac80889217950617d05/setup.cfg#L2

**Comment by sebastian-goeldi** [comment]
Hmm, that's interesting, that should be managed by `pyproject.toml` anyway
